<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>AutoDimDuctTool</RootNamespace>
    <AssemblyName>AutoDimDuctTool</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RevitVersion Condition="'$(RevitVersion)' == ''">2024</RevitVersion>
    <RevitPath Condition="'$(RevitPath)' == ''">C:\Program Files\Autodesk\Revit $(RevitVersion)</RevitPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>$(RevitPath)\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>$(RevitPath)\RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="WindowsBase" />
    <Reference Include="System.Xaml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="icon32.png">
      <LogicalName>AutoDimDuctTool.icon32.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
